# Generated by Django 5.1.4 on 2025-01-05 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('address_line', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('stock_quantity', models.IntegerField()),
                ('min_stock', models.IntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('reorder_level', models.IntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='cms.category')),
                ('supplier_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='cms.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('action', models.TextField()),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('item_name_backup', models.CharField(blank=True, max_length=255, null=True)),
                ('inventory_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item', to='cms.inventory')),
                ('supplier_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier', to='cms.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Surgery_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('typical_duration_min', models.IntegerField()),
                ('preparation_instructions', models.TextField(blank=True, null=True)),
                ('recovery_instructions', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.department')),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_full_name', models.CharField(default='patient full name', max_length=255)),
                ('schedules_start_time', models.DateTimeField()),
                ('schedules_end_time', models.DateTimeField(null=True)),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('pre_op_notes', models.TextField(blank=True, null=True)),
                ('post_op_notes', models.TextField(blank=True, null=True)),
                ('complications', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Pre-Op', 'Pre-Op'), ('In Surgery', 'In Surgery'), ('Post-Op', 'Post-Op'), ('Recovery', 'Recovery'), ('Completed', 'Completed')], default='Scheduled', max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.department')),
                ('operating_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeries', to='cms.room')),
                ('primary_surgeon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='cms.doctor')),
                ('surgery_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.surgery_type')),
            ],
        ),
    ]
