# Generated by Django 5.1.4 on 2025-01-06 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_consultation_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='appointment',
        ),
    ]
