# Generated by Django 5.1.4 on 2025-01-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='patient',
            field=models.CharField(max_length=100),
        ),
    ]
