# Generated by Django 5.1.4 on 2025-01-09 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_log_options_log_unit_backup_alter_log_action_and_more'),
        ('cms', '0007_alter_bill_patient'),
    ]

    operations = [
    ]
