# Generated by Django 5.1.4 on 2025-01-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_prescription_dosage_unit_prescription_duration_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='med_route',
            field=models.CharField(default='oral', max_length=100),
            preserve_default=False,
        ),
    ]
