# Generated by Django 5.1.4 on 2025-01-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0010_prescription_med_route"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emergencycontact",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="emergency_contact",
        ),
        migrations.RemoveField(
            model_name="medicalspecialty",
            name="specialty",
        ),
        migrations.RemoveField(
            model_name="nursespecialty",
            name="specialty",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="room",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="staff",
        ),
        migrations.DeleteModel(
            name="AuditLog",
        ),
        migrations.DeleteModel(
            name="EmergencyContact",
        ),
        migrations.DeleteModel(
            name="MedicalSpecialty",
        ),
        migrations.DeleteModel(
            name="NurseSpecialty",
        ),
        migrations.DeleteModel(
            name="Schedule",
        ),
    ]
